apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eks-demo-app-hpa
  namespace: eks-demo-app
spec:
  minReplicas: 2
  maxReplicas: 20
  scaleTargetRef:
    kind: Deployment
    name: eks-demo-app-deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
