apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: spring-boot-app-rds
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: us-west-2
    dbInstanceClass: db.t2.small
    masterUserPasswordSecretRef:
      name: postgres-dev
      key: password
      namespace: eks-demo-app
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "12.10"
    skipFinalSnapshot: true
    publiclyAccessible: false
  publishConnectionDetailsTo:
    name: dbinstance-conn
  writeConnectionSecretToRef:
    namespace: eks-demo-app
    name: aws-rdspostgresql-conn
