---
apiVersion: rds.aws.crossplane.io/v1alpha1
kind: DBInstance
metadata:
  name: eks-demo-app-rds
  namespace: eks-demo-app
spec:
  deletionPolicy: Delete
  providerConfigRef:
    name: default
  forProvider:
    region: us-west-2
    dbInstanceClass: db.t3.micro
    autoMinorVersionUpgrade: true
    masterUserPasswordSecretRef:
      name: postgres
      key: password
      namespace: eks-demo-app
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "13.12"
    skipFinalSnapshot: true
    applyImmediately: true
    publiclyAccessible: false
  publishConnectionDetailsTo:
    name: dbinstance-conn
  writeConnectionSecretToRef:
    namespace: eks-demo-app
    name: aws-rdspostgresql-conn

